import { ResearchWorkload } from './aws'

export const RESEARCH_WORKLOADS: ResearchWorkload[] = [
  {
    id: 'genome-assembly',
    name: 'Genome Assembly',
    description: 'Large-scale genome assembly and annotation pipelines',
    category: 'genomics',
    requirements: {
      minVCpus: 16,
      minMemoryGiB: 64,
      maxMemoryGiB: 512,
      requireGpu: false,
      storageType: 'any',
      architecture: 'x86_64',
    },
    estimatedRuntime: {
      min: 8,
      max: 72,
      unit: 'hours',
    },
  },
  {
    id: 'variant-calling',
    name: 'Variant Calling Pipeline',
    description: 'SNP and structural variant detection from sequencing data',
    category: 'genomics',
    requirements: {
      minVCpus: 8,
      minMemoryGiB: 32,
      maxMemoryGiB: 128,
      requireGpu: false,
      storageType: 'any',
      architecture: 'x86_64',
    },
    estimatedRuntime: {
      min: 4,
      max: 24,
      unit: 'hours',
    },
  },
  {
    id: 'protein-folding',
    name: 'Protein Folding Simulation',
    description:
      'Molecular dynamics simulations for protein structure prediction',
    category: 'genomics',
    requirements: {
      minVCpus: 4,
      minMemoryGiB: 16,
      requireGpu: true,
      minGpuMemoryGiB: 8,
      storageType: 'any',
      architecture: 'x86_64',
    },
    estimatedRuntime: {
      min: 12,
      max: 168,
      unit: 'hours',
    },
  },
  {
    id: 'climate-modeling',
    name: 'Climate Model Simulation',
    description: 'High-resolution climate and weather modeling',
    category: 'climate',
    requirements: {
      minVCpus: 32,
      minMemoryGiB: 128,
      maxMemoryGiB: 1024,
      requireGpu: false,
      networkPerformance: ['10 Gigabit', '25 Gigabit'],
      storageType: 'any',
      architecture: 'x86_64',
    },
    estimatedRuntime: {
      min: 24,
      max: 720,
      unit: 'hours',
    },
  },
  {
    id: 'satellite-processing',
    name: 'Satellite Data Processing',
    description: 'Large-scale earth observation data processing and analysis',
    category: 'climate',
    requirements: {
      minVCpus: 16,
      minMemoryGiB: 64,
      maxMemoryGiB: 256,
      requireGpu: true,
      minGpuMemoryGiB: 16,
      storageType: 'any',
      architecture: 'x86_64',
    },
    estimatedRuntime: {
      min: 6,
      max: 48,
      unit: 'hours',
    },
  },
  {
    id: 'llm-training',
    name: 'Large Language Model Training',
    description: 'Training large language models and foundation models',
    category: 'ml',
    requirements: {
      minVCpus: 16,
      minMemoryGiB: 128,
      requireGpu: true,
      minGpuMemoryGiB: 32,
      networkPerformance: ['25 Gigabit', '50 Gigabit', '100 Gigabit'],
      storageType: 'any',
      architecture: 'x86_64',
    },
    estimatedRuntime: {
      min: 48,
      max: 2160,
      unit: 'hours',
    },
  },
  {
    id: 'hyperparameter-sweep',
    name: 'Hyperparameter Optimization',
    description: 'Parallel hyperparameter tuning for ML models',
    category: 'ml',
    requirements: {
      minVCpus: 4,
      minMemoryGiB: 16,
      maxMemoryGiB: 64,
      requireGpu: true,
      minGpuMemoryGiB: 8,
      storageType: 'any',
      architecture: 'x86_64',
    },
    estimatedRuntime: {
      min: 2,
      max: 24,
      unit: 'hours',
    },
  },
  {
    id: 'inference-serving',
    name: 'ML Model Inference',
    description: 'Real-time model inference and serving',
    category: 'ml',
    requirements: {
      minVCpus: 2,
      minMemoryGiB: 8,
      maxMemoryGiB: 32,
      requireGpu: true,
      minGpuMemoryGiB: 4,
      networkPerformance: ['Up to 10 Gigabit', '10 Gigabit'],
      storageType: 'ebs',
      architecture: 'x86_64',
    },
  },
  {
    id: 'molecular-dynamics',
    name: 'Molecular Dynamics',
    description: 'Classical and quantum molecular dynamics simulations',
    category: 'chemistry',
    requirements: {
      minVCpus: 8,
      minMemoryGiB: 32,
      maxMemoryGiB: 128,
      requireGpu: true,
      minGpuMemoryGiB: 8,
      storageType: 'any',
      architecture: 'x86_64',
    },
    estimatedRuntime: {
      min: 12,
      max: 240,
      unit: 'hours',
    },
  },
  {
    id: 'quantum-simulation',
    name: 'Quantum System Simulation',
    description: 'Quantum chemistry and materials science calculations',
    category: 'physics',
    requirements: {
      minVCpus: 16,
      minMemoryGiB: 64,
      maxMemoryGiB: 512,
      requireGpu: false,
      storageType: 'any',
      architecture: 'x86_64',
    },
    estimatedRuntime: {
      min: 6,
      max: 168,
      unit: 'hours',
    },
  },
  {
    id: 'cfd-simulation',
    name: 'Computational Fluid Dynamics',
    description: 'High-fidelity fluid flow simulations and analysis',
    category: 'engineering',
    requirements: {
      minVCpus: 32,
      minMemoryGiB: 128,
      maxMemoryGiB: 512,
      requireGpu: false,
      networkPerformance: ['10 Gigabit', '25 Gigabit'],
      storageType: 'any',
      architecture: 'x86_64',
    },
    estimatedRuntime: {
      min: 24,
      max: 480,
      unit: 'hours',
    },
  },
  {
    id: 'finite-element',
    name: 'Finite Element Analysis',
    description: 'Structural analysis and materials modeling',
    category: 'engineering',
    requirements: {
      minVCpus: 16,
      minMemoryGiB: 64,
      maxMemoryGiB: 256,
      requireGpu: false,
      storageType: 'any',
      architecture: 'x86_64',
    },
    estimatedRuntime: {
      min: 8,
      max: 120,
      unit: 'hours',
    },
  },
]
